### ISSUE TITLE
Leak between block 

### ISSUE THREAD

**Issue by 24hours** [AlexSTV/Voxelmetric#2] opened 2015-05-16 14:43 UTC
The mesh between 2 blocks have some sort of leak. 
![screen shot 2015-05-16 at 10 49 01 pm](https://cloud.githubusercontent.com/assets/650407/7666530/54d83726-fc24-11e4-94e5-53484ee9a547.png)

The problem is because how chunk is constructed, mesh between blocks are disconnected. 
The solution is quite straight forward, just remove duplicate vertices from meshData.vertices and rearrange meshData.triangle. 

Do you have any intention or idea to fix this problem.

**Comment by AlexSTV** [comment] 2015-05-17 15:40
I've taken a look at sharing vertices before but I can't figure out how to create the UVs when vertices are shared. Since UVs are applied per vertex two neighbouring quads can't have different UV values for their shared vertices. I'm not sure how other people have solved this.

**Comment by 24hours** [comment] 2015-05-18 09:43
I might try to look it up as well. Since 1 block should be able to have multiple texture overlay on top. This feature is required when implementing "footstep" on snow block. 

will revisit this issue again after I  googled around.

**Comment by AlexSTV** [comment] 2015-06-23 17:50
I'm closing this for now, will open it if anyone confirms the issue is still present.

**Closed by AlexSTV** 2015-06-23 17:50 UTC
Labels: bug, confirmed, in test
